apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  name: jenkins-deploy
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.235.1-lts
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: pv-storage
