apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
    - port: 8080
      name: master    # Set a the port's name
    - port: 50000     # Enable port for executors
      name: executors # Set a the port's name
  selector:
    app: jenkins