apiVersion: v1
kind: Pod
metadata:
  name: brezyweather
  labels:
    app: brezyweather-app
spec:
  containers:
    - name: brezyweather-app
      image: nginx
      env:
      - name: SECRET_API
        valueFrom:
          secretKeyRef:
            key: openweather-key
            name: test-secret
      volumeMounts:
        - mountPath: /etc/config
          name: db-connection-secret
  volumes:
    - name: db-connection-secret
      secret:
        secretName: db-secret