apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-pod
  name: app-pod
  namespace: prod-env
spec:
  containers:
  - command:
    - ping
    - localhost
    image: busybox
    name: app-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
  restartPolicy: Always
status: {}