apiVersion: v1
kind: Service
metadata:
  name: brezyweather-service
spec:
  selector:
    app: myapp
    version: blue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer